name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: ghcr.io

jobs:
  main:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Variables
        id: get-variables
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          echo ::set-output name=gh-username-lower::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Build and push Cuda Image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/cuda.Dockerfile
          platforms: linux/arm64
          tags: ${{ env.REGISTRY }}/dickeyf:${{ env.TAG }}-cuda
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: with_models=true
        env:
          TAG: ${{ startsWith(github.ref, 'refs/tags/') && steps.get-variables.outputs.version || 'latest' }}
